[package]
name = "Amethyst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.5"
format_num = "0.1.0"
num = "0.4.0"
foreach = "0.3.0"